"""
Django settings for trader project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "v4-e$8d2u+7&=a3gg#+2%oom-u!_2%q@b688d=amdfv-i7x116"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", True)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "trader.urls"

TEMPLATE_BASE = "templates"
TEMPLATE_DIR = os.path.join(BASE_DIR, TEMPLATE_BASE)
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "trader.wsgi.application"


# Database

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"


# if DEBUG:
#     load_dotenv("../.trader-env")

if os.environ.get("ENVIRONMENT") == None:
    MONGO_URL = "localhost"
    MONGO_PORT = str(27017)
    MONGO_URI = "mongodb://" + MONGO_URL + ":" + MONGO_PORT + "/"
    DEBUG = True
    SECRET_KEY = "secret"
elif os.environ.get("ENVIRONMENT") == "production":
    MONGO_USER = os.environ["MONGO_USER"]
    MONGO_PASSWORD = os.environ["MONGO_PASSWORD"]
    MONGO_URL = os.environ["MONGO_URL"]
    MONGO_PORT = os.environ["MONGO_PORT"]
    MONGO_DBNAME = os.environ["MONGO_DBNAME"]
    MONGO_URI = (
        "mongodb://"
        + MONGO_USER
        + ":"
        + MONGO_PASSWORD
        + "@"
        + MONGO_URL
        + ":"
        + MONGO_PORT
        + "/"
        + MONGO_DBNAME
    )
    DEBUG = False
    SECRET_KEY = os.environ["SECRET_KEY"]
